name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run-script build
      - name: Pack Artifacts
        run: mkdir staging; cd dist; zip -r ../staging/ngx-boring-avatars.zip *; tar -cvzf ../staging/ngx-boring-avatars.tar.gz *;
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging
